ls:
  src/components:
    .dir: PascalCase | lowercase
    .module.scss: PascalCase
    .props.tsx: PascalCase
    .tsx: PascalCase | lowercase
  src/hooks:
    .dir: camelCase | lowercase
    .tsx: camelCase | lowercase
  src/layouts:
    .dir: PascalCase | lowercase
    .module.scss: PascalCase
    .props.tsx: PascalCase
    .tsx: PascalCase | lowercase
  src/pages:
    .dir: kebab-case | lowercase
    .tsx: kebab-case | lowercase
  src/styles:
    .dir: kebab-case | lowercase
    .tsx: kebab-case | lowercase
    .module.scss: PascalCase
    .scss: kebab-case | lowercase
